// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/auth/login': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/login.post').default>>>>
    }
    '/api/friends/:id': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/friends/[id].delete').default>>>>
    }
    '/api/friends': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/friends/index.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/friends/index.post').default>>>>
    }
    '/api/friends/requests': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/friends/requests.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/friends/requests.post').default>>>>
    }
    '/api/friends/requests/:id': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/friends/requests/[id].delete').default>>>>
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/friends/requests/[id].put').default>>>>
    }
    '/api/messages/:id': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/messages/[id].delete').default>>>>
    }
    '/api/messages': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/messages/index.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/messages/index.post').default>>>>
    }
    '/api/migrate': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/migrate.post').default>>>>
    }
    '/api/posts/:id': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/posts/[id].delete').default>>>>
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/posts/[id].get').default>>>>
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/posts/[id].put').default>>>>
    }
    '/api/posts': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/posts/index.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/posts/index.post').default>>>>
    }
    '/api/r2/**:path': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/r2/[...path].get').default>>>>
    }
    '/api/upload/image': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/upload/image.post').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/@nuxt/nitro-server/dist/runtime/handlers/renderer').default>>>>
    }
    '/__nuxt_island/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/#internal/nuxt/island-renderer').default>>>>
    }
  }
}
export {}